services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb-users
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: userdb
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
